Revert 00002 migration name to previous name when migration fails because of it
nhost/hasura-auth pull request #134
Opened 2022-04-03 21:35 UTC by plmercereau

@nunopato @elitan we modified migration file names in previous versions
It turns out it was not a good idea: while Hasura migration system seems to ignore such name changes, `@djgrant/postgres-migrations` is not happy with it as it checks hashes from file names.

This fix is not elegant, but it's the only way that I've seen so far to handle the following cases:

- migration from 0.2 (`_` name) to further versions (`-` name)
- migration from 0.3 (`-` name) to further versions (`-` name)

closes #129

2022-04-04 07:04 UTC, elitan requested changes

2022-04-04 07:04 UTC, elitan commented on src/migrations.ts
> +    const userFieldsMigration = path.join(
Could you add an inline comment so we know why this code is here when we look at this 3+ months from now

2022-04-04 08:34 UTC, elitan approved these changes

2022-04-20 11:04 UTC, mmmmillar commented
Hi, is this likely to go in soon? I haven't been able to update because of it. Thanks

2022-04-20 16:59 UTC, merged