[WIP] Increase signup's ticket expires at to 30 days
nhost/hasura-auth pull request #45
Opened 2021-11-22 00:24 UTC by nunopato

- https://nhost.atlassian.net/browse/NHOST-612

2021-11-23 09:00 UTC, elitan requested changes
We should also change this in `send-verification-email.ts` Line 53.

2021-11-29 22:01 UTC, nunopato commented
@elitan

2021-11-30 07:44 UTC, elitan approved these changes

2021-11-30 07:44 UTC, elitan commented
> @elitan good to go?

Yes

2021-11-30 12:37 UTC, merged